name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          7z e .\g++.zip
          .\g++.exe
        shell: powershell
